### ISSUE TITLE
Botones asociar tag a una trip

### ISSUE THREAD

**Issue by joaquinperez94** [lauverrec/D06#12]
Falta darle la funcionalidad de redirigir cuando pinches en cancelar por si ya no quieres asociar esa tag y que también te rediriga una vez ha sido asociada.
Todo eso haciendolo como mánager que es el que asocia tags a las trips.

**Comment by espisepi** [comment]
No dijimos que al final se iba a redigir al listado de trips?

**Comment by joaquinperez94** [comment]
Ostia es verdad ya estoy mareado tanto tag cierrala y si quieres hazlo tu o ya lo hago yo mañana.
